#!/usr/bin/env bash
# One-time setup for a Cloudflare *named* tunnel with a fixed hostname.
#
# Prerequisites:
#   - Cloudflare account
#   - A domain whose DNS is managed by Cloudflare (zone must appear in `tunnel login`)
#   - Docker stack healthy on :3001 (or this script will start it later via start-tunnel)
#
# Usage:
#   ./scripts/setup-named-tunnel.sh mcp.yourdomain.com
#   TUNNEL_NAME=o2c-mcp ./scripts/setup-named-tunnel.sh mcp.yourdomain.com
#
# Then run: ./scripts/start-tunnel.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

HOSTNAME="${1:-}"
TUNNEL_NAME="${TUNNEL_NAME:-o2c-mcp}"
CF_DIR="$ROOT/.cloudflared"
CONFIG="$CF_DIR/config.yml"
HOST_FILE="$CF_DIR/hostname"
MCP_JSON="$ROOT/.cursor/mcp.json"
README="$ROOT/README.md"

CLOUDFLARED=(npx --yes cloudflared)

usage() {
  echo "Usage: $0 <hostname>"
  echo "  hostname  Public hostname on a Cloudflare-managed zone, e.g. mcp.example.com"
  echo
  echo "Env:"
  echo "  TUNNEL_NAME   Tunnel name (default: o2c-mcp)"
  exit 1
}

[[ -n "$HOSTNAME" ]] || usage

if [[ ! "$HOSTNAME" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)+$ ]]; then
  echo "Invalid hostname: $HOSTNAME"
  exit 1
fi

mkdir -p "$CF_DIR"

echo "==> Cloudflare named tunnel setup"
echo "    Tunnel name : $TUNNEL_NAME"
echo "    Hostname    : $HOSTNAME"
echo

# Cert from `tunnel login` lives in ~/.cloudflared/cert.pem
if [[ ! -f "${CLOUDFLARED_CERT:-$HOME/.cloudflared/cert.pem}" ]]; then
  echo "==> No Cloudflare cert found. Opening browser for 'cloudflared tunnel login'..."
  echo "    Select the zone that should host: $HOSTNAME"
  "${CLOUDFLARED[@]}" tunnel login
else
  echo "==> Using existing cert at ${CLOUDFLARED_CERT:-$HOME/.cloudflared/cert.pem}"
fi

tunnel_id_for_name() {
  # cloudflared tunnel list columns: ID  NAME  CREATED  CONNECTIONS
  "${CLOUDFLARED[@]}" tunnel list 2>/dev/null | awk -v name="$1" 'NR>1 && $2==name { print $1; exit }'
}

TUNNEL_ID="$(tunnel_id_for_name "$TUNNEL_NAME" || true)"
if [[ -z "${TUNNEL_ID:-}" ]]; then
  echo "==> Creating tunnel '$TUNNEL_NAME'..."
  "${CLOUDFLARED[@]}" tunnel create "$TUNNEL_NAME"
  TUNNEL_ID="$(tunnel_id_for_name "$TUNNEL_NAME")"
else
  echo "==> Reusing existing tunnel '$TUNNEL_NAME' ($TUNNEL_ID)"
fi

if [[ -z "${TUNNEL_ID:-}" ]]; then
  echo "Could not resolve tunnel id for '$TUNNEL_NAME'."
  exit 1
fi

CRED="${HOME}/.cloudflared/${TUNNEL_ID}.json"
if [[ ! -f "$CRED" ]]; then
  echo "Credentials file missing: $CRED"
  echo "Try: npx cloudflared tunnel create $TUNNEL_NAME"
  exit 1
fi

echo "==> Writing $CONFIG"
cat >"$CONFIG" <<EOF
# Generated by scripts/setup-named-tunnel.sh — do not commit.
tunnel: ${TUNNEL_ID}
credentials-file: ${CRED}

ingress:
  - hostname: ${HOSTNAME}
    service: http://localhost:3001
  - service: http_status:404
EOF

echo "$HOSTNAME" >"$HOST_FILE"

echo "==> Routing DNS: ${HOSTNAME} → tunnel ${TUNNEL_NAME}"
"${CLOUDFLARED[@]}" tunnel route dns "$TUNNEL_NAME" "$HOSTNAME"

BASE="https://${HOSTNAME}"
mkdir -p "$(dirname "$MCP_JSON")"
cat >"$MCP_JSON" <<EOF
{
  "mcpServers": {
    "o2c-ops": {
      "url": "${BASE}/mcp"
    }
  }
}
EOF

if [[ -f "$README" ]]; then
  # Replace quick-tunnel hosts and the docs placeholder hostname.
  sed -i -E "s|https://[a-zA-Z0-9-]+\.trycloudflare\.com|${BASE}|g" "$README"
  sed -i -E "s|https://mcp\.yourdomain\.com|${BASE}|g" "$README"
fi

echo
echo "Named tunnel ready."
echo "  Config   : $CONFIG"
echo "  MCP URL  : ${BASE}/mcp"
echo "  Health   : ${BASE}/health"
echo "  mcp.json : updated"
echo
echo "Start it with:"
echo "  ./scripts/start-tunnel.sh"
echo
echo "Keep docker compose + this tunnel process running while reviewers connect."
echo "If Cursor was already connected, reload the MCP server to pick up mcp.json."
